Change format check to format:fix with git diff to show what changed

diff --git a/.github/workflows/firebase-hosting-pull-request.yml b/.github/workflows/firebase-hosting-pull-request.yml
--- a/.github/workflows/firebase-hosting-pull-request.yml
+++ b/.github/workflows/firebase-hosting-pull-request.yml
@@ -29,7 +29,9 @@ jobs:
 
       - name: Format App
         working-directory: ./App
-        run: npm run format:check
+        run: |
+          npm run format:fix
+          git diff --exit-code || (echo "::error::Files were not formatted correctly. Please run 'npm run format:fix' locally and commit the changes." && exit 1)
 
       - name: Lint App
         working-directory: ./App
